variables:
  DOCKER_IMAGE: my-docker-image

stages:
  - build
  - test
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  image: maven:latest
  stage: test
  script:
    - mvn test

deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag $DOCKER_IMAGE $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
